### PR TITLE
De emphasize column section

### PR DESCRIPTION
**Pull request by TimOsahenru**
## Issue Link 🔗:

**Issue**: #553 

## Type of Change

- [x] Bug fix 🐞
- [ ] New feature/page
- [ ] Documentation update
- [ ] Other

## Description 📋
Reduced the font size of title for recent news

## Checklist ✅

- [x] Followed the [Code of Conduct](https://github.com/BlackPythonDevs/blackpythondevs.github.io?tab=coc-ov-file) and [Contribution Guide](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/469afd71943738b7209bfe56d5a4e35394fbaafc/CONTRIBUTING.md)
- [x] Ran `pre-commit run --all`
- [x] All tests pass locally
- [ ] Added tests (if applicable)
- [ ] Documentation updated (if applicable)

## Additional Notes & Screenshots

image

### CODE REVIEW

**Comment by kjaymiller** [comment]
I see there are two of these now... Can you explain the disconnect?

**Comment by TimOsahenru** [comment]
> I see there are two of these now... Can you explain the disconnect?

I think I somehow pulled all the changes I have been making into this last pull request, while the other one just has specific fixes.

**Comment by kjaymiller** [comment]
Can you fix the pre-commit issue?

**Comment by TimOsahenru** [comment]
> Can you fix the pre-commit issue?

Fixed. Please check it out

**Pull request merged**
