### PR TITLE
Fixed broken youtube link

### LINKED ISSUE #539: Investigate and fix broken youtube link in post article
Investigate and fix the broken YouTube link in this blog post. https://blackpythondevs.com/2024-10-19-black-python-devs-leadership-summit/

### PR DESCRIPTION
**Pull request by TimOsahenru**
## Issue Link 🔗:

**Issue**: #539 

## Type of Change

- [x] Bug fix 🐞
- [ ] New feature/page
- [ ] Documentation update
- [ ] Other

## Description 📋

Fixed broken youtube link in post article

## Checklist ✅

- [x] Followed the [Code of Conduct](https://github.com/BlackPythonDevs/blackpythondevs.github.io?tab=coc-ov-file) and [Contribution Guide](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/469afd71943738b7209bfe56d5a4e35394fbaafc/CONTRIBUTING.md)
- [x] Ran `pre-commit run --all`
- [x] All tests pass locally
- [ ] Added tests (if applicable)
- [ ] Documentation updated (if applicable)

## Additional Notes & Screenshots

Add any additional notes or comments that might be helpful for the reviewers.

### CODE REVIEW

**Review by kjaymiller — APPROVED** [review]
LGTM

**Comment by kjaymiller** [comment]
@TimOsahenru do you have the ability to merge your PRs?

**Comment by TimOsahenru** [comment]
> @TimOsahenru do you have the ability to merge your PRs?

Yes, I have merge rights, but I’m all for having an extra pair of eyes review my PRs first to help ensure quality and alignment with our standards

**Comment by kjaymiller** [comment]
Correct... I had already approved and wanted to make sure that you weren't waiting for me to merge it.

**Pull request merged**
