### PR TITLE
 Create Dedicated support page #456 

### PR DESCRIPTION
**Pull request by JohananOppongAmoateng**
## Issue Link 🔗: https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/456

**Issue**: #456 

## Type of Change

- [X ] New feature/page

## Description 📋
Created a dedicated support page that has the commit change embed and an embed of our PITCH DECK

## Checklist ✅

- [ x] Followed the [Code of Conduct](https://github.com/BlackPythonDevs/blackpythondevs.github.io?tab=coc-ov-file) and [Contribution Guide](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/469afd71943738b7209bfe56d5a4e35394fbaafc/CONTRIBUTING.md)
- [x ] Ran `pre-commit run --all`
- [ x] All tests pass locally

### CODE REVIEW

**Comment by kjaymiller** [comment]
@JohananOppongAmoateng can you add the support page to the routes to be tested here - 

https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/12b0f749e24d00994ba24895c43534cfd520b1c7/tests/conftest.py#L14-L22

**Review by kjaymiller — CHANGES_REQUESTED** [review]
Add file to test and then we can merge

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller  noted will do that

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller added the file to test routes

**Review by kjaymiller — APPROVED** [review]

**Pull request merged**
