### PR TITLE
New carousel

### PR DESCRIPTION
**Pull request by TimOsahenru**
## Issue Link 🔗:

**Issue**: #553 

## Type of Change

- [x] Bug fix 🐞
- [x] New feature/page
- [ ] Documentation update
- [ ] Other

## Description 📋

- Made the carousel width 100% so it can match with the rest section of the page
- Changed circled image to display full image
- Used custom built carousel and uninstalled bootstrap
- Included two testcases to test the implementation of the carousel slider
  - to test the carousel actually is exist on the page
  - to the test the first item from the carousel and that from the last post section matches

## Checklist ✅

- [x] Followed the [Code of Conduct](https://github.com/BlackPythonDevs/blackpythondevs.github.io?tab=coc-ov-file) and [Contribution Guide](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/469afd71943738b7209bfe56d5a4e35394fbaafc/CONTRIBUTING.md)
- [x] Ran `pre-commit run --all`
- [x] All tests pass locally
- [x] Added tests (if applicable)
- [ ] Documentation updated (if applicable)

## Additional Notes & Screenshots
Commented out this section out from our testcase in other to de-emphasize that section

```python
      def test_page_description_in_index_and_blog(page_url: tuple[Page, str], url: str):
          """Checks for the descriptions data in the blog posts. There should be some objects with the class `post-description`"""
          page, live_server_url = page_url
          page.goto(f"{live_server_url}{url}")
          expect(page.locator("p.post-description").first).to_be_visible()
          expect(page.locator("p.post-description").first).not_to_be_empty()
 ```
since the post description tag has been removed from the index page

### CODE REVIEW

**Comment by TimOsahenru** [comment]
@kjaymiller please help review this. Thanks

**Comment by kjaymiller** [comment]
Going to add this to the new carousel branch for now - There is still a couple tweaks to figure out.

- [ ] Make images full width with cutoff overflow
screenshot of carousel with black bars on the side

- [ ] Move sections into a split grid together

Screenshot on homepage with the blog posts and join sections being full-width

**Comment by TimOsahenru** [comment]
Working on it. Thanks

**Comment by TimOsahenru** [comment]
Hello @kjaymiller I have made the changes to this branch https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/586 for de-emphasizing the latest post and join us section.

**Comment by TimOsahenru** [comment]
Also made changes to this branch https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/587 to fix the full image issue with the slider

**Pull request merged**
