### PR TITLE
Update a_link color in bpd.css

### PR DESCRIPTION
**Pull request by Fahass**
Update A11y link color, (Issue: #156)

### CODE REVIEW

**Review by oleksis — COMMENTED** [review]
Is not only the color for the `a` element in the Menu, we need set the color for All the `a` elements . Read this comment in the [#156](https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/156#issue-1999292648)

**Comment by Fahass** [comment]
Okay @oleksis I will try and work on that right away!

**Comment by oleksis** [comment]
Small steps to get resolved
- Reproduce the Ay11 issues and share **Web Capture**
image
- Make the changes for fix the issues (CSS)
- Test the changes, run the **FastPass** test and take the Web Capture with no issues for A11y 
image
- Check and pass others test like the rules with `pre-commit`

**Comment by oleksis** [comment]
@Fahass Thanks for the contributions!

**Comment by Fahass** [comment]
It's my pleasure @oleksis

**Pull request merged**
