### PR TITLE
[Fix Documentation] remove CONTRIBUTING.md

### LINKED ISSUE #317: [Documentation] remove CONTRIBUTING.md
### Current Behavior

Currently the CONTRIBUTING.md needs to be applied to projects manually on each project.

### Desired Situation
To automatically add the CONTRIBUTING.md to all projects it will first be removed from each project and added to [.github](https://www.github.com/BlackPythonDevs/.github).

### PR DESCRIPTION
**Pull request by sandramsc**
This PR fixes #317

### CODE REVIEW

**Comment by oleksis** [comment]
i think is no good idea. If some new contributors checkout/clone/fork the repository they dont have the CONTRIBUTING.md. The CONTRIBUTING.md is specific to this repository.

**Comment by kjaymiller** [comment]
@sandramsc I apologize on this one as I gave the green light faster than folks had time to discuss. 

Normally I would disagree that you should have individual contributing files unless absolutely necessary but  I understand @oleksis's point in that there are some instructions that are specific to this project. 

### I Propose this compromise

- We still remove the contributing but after creating a "Deploying, Running and Testing Section" in the README.

My justification for this is that perhaps the `Contributing.md` should be all the things to contribute to projects and not to work on the code itself.

Usually run and testing steps are in the documentation and the closest thing to documentation we would have is the README.

I would love thoughts on this.

**Comment by sandramsc** [comment]
> @sandramsc I apologize on this one as I gave the green light faster than folks had time to discuss. 
> 
> Normally I would disagree that you should have individual contributing files unless absolutely necessary but  I understand @oleksis's point in that there are some instructions that are specific to this project. 
> 
> ### I Propose this compromise
> 
> - We still remove the contributing but after creating a "Deploying, Running and Testing Section" in the README.
> 
> My justification for this is that perhaps the `Contributing.md` should be all the things to contribute to projects and not to work on the code itself.
> 
> Usually run and testing steps are in the documentation and the closest thing to documentation we would have is the README.
> 
> I would love thoughts on this.

Perhaps adding the run and testing steps to the README.md is not uncommon, and would **+1** on the idea, especially if the CONTRIBUTING.md is unique to each repo, it'll be reasonable to keep these separate.

**Comment by oleksis** [comment]
Will close the PR ?

**Comment by kjaymiller** [comment]
@oleksis - I wouldn't  close yet. I think there is some more conversation that is happening that may apply to this work.

@sandramsc - are you thinking about moving the contents to the README or would this be done in another PR?

**Comment by sandramsc** [comment]
> @oleksis - I wouldn't close yet. I think there is some more conversation that is happening that may apply to this work.
> 
> @sandramsc - are you thinking about moving the contents to the README or would this be done in another PR?

I'm thinking that steps on how to contribute should remain in CONTRIBUTING.md and tests, how to run the app/repo etc. could be added there as well or the README.md (leaning towards them being placed in README.md, but I've seen them in CONTRIBUTING.md as well)

**Comment by kjaymiller** [comment]
If your plan is to have them in both then we can close this and add the README changes to a new PR. That being said @sandramsc - if that's your preference you should be able to close this PR and we'll let you do that when you feel you have all the things you need.

**Comment by sandramsc** [comment]
Status:

- Retaining CONTRIBUTING.md with current content, but moving running, tests, how to use the project in the README.md

**Pull request closed without merging**
