### PR TITLE
 Update headers to be to follow accessibility guidelines in book-club.html #491 

### LINKED ISSUE #491: Update headers to be to follow accessibility guidelines in book-club.html
https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/7bc8db1203900cc29555a87114c28820a8d65f41/book-club.html#L18-L23

Currently the h3 comes before the h2. These should be reversed.

### PR DESCRIPTION
**Pull request by JohananOppongAmoateng**
Reversed the h2 and h3 headers 
Close #491

### CODE REVIEW

**Comment by kjaymiller** [comment]
It seems there are changes that were a part of a different PR. Can you update your code base and rebase it to only include the changes that are a part of this change?

**Review by kjaymiller — CHANGES_REQUESTED** [review]
Rebase code to only include changes that connected to the issue.

**Comment by JohananOppongAmoateng** [comment]
Okay 👍

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller closing pr seems @Brijeshthummar02 opened a pr for this

**Pull request closed without merging**
