### PR TITLE
run pre-commit install in the devcontainer

### LINKED ISSUE #46: run pre-commit install in the devcontainer
New contributors often get pre-commit failures in their PR. 

pre-commit is installed in the devcontainer but the setup never happens.

## To Fix

We can add that first run to our `postCreateCommand` in the [devcontainer](https://containers.dev/implementors/spec/#merge-logic)

### PR DESCRIPTION
**Pull request by oleksis**
Fixes #46

### CODE REVIEW

**Comment by kjaymiller** [comment]
@oleksis - I assume we still need the other commands to be ran as well...

I would suggest creating a simple shell script with all the commands and calling the shell script in the postCreateCommand.

**Comment by oleksis** [comment]
What other commands you think we need to use ?

**Comment by kjaymiller** [comment]
I think just the ones that we originally had added (`pip install` and `playwright`). I believe that black gets installed with pre-commit so we don't need that but we do need the playwright install...


```shell
pre-commit install
python -m playwright install --with-deps
```

**Comment by oleksis** [comment]
> ```shell
> python -m playwright install --with-deps
> ```

Install Playwright with dependencies on "postCreateCommand" is slow if we rebuild the devcontainer. We install Python developments requirements and playwright dependencies on build time of the container to reuse the cache.

The Jekyll base image run the "postCreateCommand" and install Bundler and the Gemfile dependencies

If we need run others commands on post-create we can update the `.devcontainer\post-create-bpdevs.sh` shell script file

@kjaymiller

**Pull request merged**
