### PR TITLE
Updated mission statements which fixes #95

### PR DESCRIPTION
**Pull request by TimOsahenru**
Updated the README, about and banner home page with our new mission statements "Extending the ecosystem of Python Communities to Black and Colo(u)red Communities around the world."

### CODE REVIEW

**Comment by kjaymiller** [comment]
@TimOsahenru - please run pre-commit to lint your code. (That will fix the failing test)

**Comment by kjaymiller** [comment]
@TimOsahenru - Do you need help with getting the pre-commit passing?

**Comment by TimOsahenru** [comment]
> @TimOsahenru - Do you need help with getting the pre-commit passing?

Yes please. When I run the command `pre-commit run` it takes forever without making changes to any file

**Comment by kjaymiller** [comment]
> > @TimOsahenru - Do you need help with getting the pre-commit passing?
> 
> Yes please. When I run the command `pre-commit run` it takes forever without making changes to any file

did you run ` pre-commit run --all` to update all

**Comment by kjaymiller** [comment]
lol great minds. That should fix it.

**Pull request merged**
