### PR TITLE
Create events template #4

### PR DESCRIPTION
**Pull request by VeldaKiara**
The event template to create future events.

### CODE REVIEW

**Comment by oleksis** [comment]
[Issues and Pull Requests Templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)

Can move the `yml` file to the `.github/ISSUE_TEMPLATE` folder 

> issue templates must be located in the `.github/ISSUE_TEMPLATE` folder

**Comment by oleksis** [comment]
Can open a issue related to this pull request please?

Others docs about [configuring the template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

**Comment by VeldaKiara** [comment]
I should move the folder or delete the folder and add the `event_template.yml` file to the issue_template folder?

**Comment by VeldaKiara** [comment]
I have understood, pushing changes in a second

**Comment by oleksis** [comment]
Good 👍🏾 Now apply `pre-commit run --all-files --show-diff-on-failure` and push the changes

**Comment by VeldaKiara** [comment]
Thanks for the help @oleksis!

**Review by oleksis — APPROVED** [review]
Good work!

**Pull request merged**
