### PR TITLE
[Fix How to Use Section] - add a "How to Use" section to the README.md

### LINKED ISSUE #325: [How to Use Section] - add a "How to Use" section to the README.md
### Current Behavior

Following through with this comment  --> [#313 ](https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/318#issuecomment-2100593554)

### Desired Situation
Update the README.md with relevant steps on "How to Use" the app/repo

### PR DESCRIPTION
**Pull request by sandramsc**
This PR fixes #325

### CODE REVIEW

**Comment by sandramsc** [comment]
Suggestions on how to improve formatting, content included, excluded in both changed files and how to enhance if need be are welcome!

**Comment by kjaymiller** [comment]
Have you ran `pre-commit run --all`

There is a linting issue that is likely a minor markdown issue.

**Comment by oleksis** [comment]
You can run `pre-commit run --all-files`

**Comment by sandramsc** [comment]
@kjaymiller @oleksis Thank you both for the feedback, having WiFi connectivity issues, will fix as soon as bandwidth is more consistent.

**Pull request merged**
