### PR TITLE
Differentiate colors for date and description on blog page

### PR DESCRIPTION
**Pull request by Ngazetungue**
## Issue Link 🔗:https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/557

**Issue**: #[557]

## Type of Change

- [ ] Bug fix 🐞
- [ ] New feature/page
- [ ] Documentation update
- [ *] Other

## Description 📋

- **What:** Provide an overview of the issue this PR addresses. Explain the context and background information.

This PR aims to improve the visual hierarchy and readability on the blog page. Right now, the font sizes and colors for the date and description text are the same or identical, which impacts the user experience by making it difficult to distinguish between the two.

### **Why:** Describe why the changes are being made. Highlight key updates, new features, or bug fixes.

The changes aim to:

1. Improve visual hierarchy, ensuring the date is visually secondary to the description.
2. Enhance readability by distinguishing the less significant metadata (date) from the main content (description).
3. Align with standard UX practices for content presentation on blogs.

### **How:** Explain how these changes will affect the project or end-users.

These changes will make the blog page more user-friendly and visually appealing for visitors. By adjusting the styling:

- **Better Readability:** The clear distinction between metadata, links, and author info will make it easier for users to quickly scan and understand the content.
- **Improved Navigation:** Links will stand out more, helping users easily find and interact with important content.
- **Increased Engagement:** Highlighting the author’s name makes it more prominent, encouraging readers to connect with the creator of the post.
- **Polished Look:** Overall, these tweaks create a more professional and cohesive design, enhancing the overall user experience.

## Checklist ✅

- [ ] Followed the [Code of Conduct](https://github.com/BlackPythonDevs/blackpythondevs.github.io?tab=coc-ov-file) and [Contribution Guide](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/469afd71943738b7209bfe56d5a4e35394fbaafc/CONTRIBUTING.md)
- [ ] Ran `pre-commit run --all`
- [ ] All tests pass locally
- [ ] Added tests (if applicable)
- [ ] Documentation updated (if applicable)

## Additional Notes & Screenshots

**Here are the screenshot of the changes**

Screenshot 2024-12-03 at 10 49 21

The Author and the Date

Screenshot 2024-12-03 at 10 49 57

### CODE REVIEW

**Comment by kjaymiller** [comment]
@Ngazetungue 

Thank you for the update on this! Can you update your description to explain the reason for your changes. Also if there is no issue explaining why the change is necessary please file and issue. 

~This is important as it can be used to defend the changes in the future.~

#### [UPDATE]

I noticed the issue already filed. If you fix pre-commit and update your PR description

**Comment by kjaymiller** [comment]
I also notice that pre-commit is failing... This can often be resolved by running 

`pre-commit run --all`

**Review by kjaymiller — CHANGES_REQUESTED** [review]
See comments

**Comment by kjaymiller** [comment]
@Ngazetungue - let me know if you need any assistance with pre-commit

**Comment by Ngazetungue** [comment]
> I also notice that pre-commit is failing... This can often be resolved by running
> 
> `pre-commit run --all`

Do i have to run this on my PR locally?

**Comment by kjaymiller** [comment]
> > I also notice that pre-commit is failing... This can often be resolved by running
> > `pre-commit run --all`
> 
> Do i have to run this on my PR locally?

Yes

**Comment by Ngazetungue** [comment]
I believe everything fixed now. @kjaymiller check it out

**Review by kjaymiller — APPROVED** [review]

**Pull request merged**
